Feature/back end
IvanKoigerov/hacker-news pull request #4
Opened 2022-08-05 15:14 UTC by IvanKoigerov

2022-08-06 15:36 UTC, crutch12 commented
отдал @Stilwuc

2022-08-08 13:27 UTC, Stilwuc requested changes

2022-08-08 13:27 UTC, Stilwuc commented on client/src/services/NewsService.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost/api' }),
baseUrl лучше в переменные окружения вынести.
А то сейчас ты локально без докера не поднимешь фронт, так как прокси nginx не будет

2022-08-08 13:27 UTC, Stilwuc commented on server/Dockerfile
> +CMD ["npm", "run", "start:prod"]
Забыл npm run build сделать, а то у тебя это работала так как лолькально было сбилжено, если не билдить самому то будет проблема

2022-08-08 13:27 UTC, Stilwuc commented on server/prisma/schema.prisma
> +  comments_count Int?
Это должно быть вычисляемым на бэке

2022-08-08 13:27 UTC, Stilwuc commented on server/index.ts
> +            comments: false,
Если не хочешь include то и не пиши просто его)

2022-08-08 13:27 UTC, Stilwuc commented on server/index.ts
> +                    comments: true,
Ну тут то я в теме)
Вообщем сам понимаешь 2 уровня вложенности не больше сейчас работает.
В идеале бы поправить чтобы можно было больше

2022-08-08 13:27 UTC, Stilwuc commented on server/index.ts
> +    for (let i = 0; i < 4; i++) {
Лучше юзать функциональный подход (forEach, map) когда можно.
Тут можно, Promise.all + map

2022-08-08 13:28 UTC, Stilwuc commented
@IvanKoigerov  А так отлично офк, небольшие штучки поправь и летим мержить

2022-08-08 15:15 UTC, IvanKoigerov commented on client/package.json
> +    "@prisma/client": "^4.1.1",
забыл((

2022-08-08 15:55 UTC, IvanKoigerov commented on client/src/page/NewsPage.tsx
> +  // const { newsArr, isLoading, refetch, isFetching } = useNews();
Соре, я их на всякий случай просто оставил, думал может надо и то и то выводить

2022-08-08 18:59 UTC, IvanKoigerov commented
А я дебил
класную метку словил получается

2022-08-08 20:48 UTC, crutch12 commented
Даня, ты чё комменты трёшь?

2022-08-08 20:59 UTC, Stilwuc commented
> Даня, ты чё комменты трёшь? Ещё и чужие

Нет конечно 😏 
![image](https://user-images.githubusercontent.com/44724024/183513478-7483045a-9934-4005-bf19-87f2a6403956.png)

2022-08-08 21:00 UTC, crutch12 commented
А спрашиваю зачем)

2022-08-08 21:03 UTC, crutch12 commented on Dockerfile
> +FROM nginx:1.23-alpine
А я вот не понимаю зачем

2022-08-08 21:04 UTC, crutch12 commented on Dockerfile
> +FROM nginx:1.23-alpine
Нашёл, там же ещё несколько докерфайлов
Сыглы.

2022-08-08 21:42 UTC, Stilwuc commented
> А спрашиваю зачем)

Я там мем скинул, потом понял что не смешной)
(Не по теме коммент был)

2022-08-08 21:46 UTC, IvanKoigerov commented on server/prisma/schema.prisma
> +  comments_count Int?
Кст я подумал, а можно триггер написать, чтобы он сам все это делал?
На призме вообще можно писать триггеры?

2022-08-08 21:56 UTC, Stilwuc commented on server/prisma/schema.prisma
> +  comments_count Int?
Да можно в принципе, там есть хуки.
Но я думаю что все же лучше через runtime подставлять, более рабочая тема.
Но в плане оптимизации через тригер и хранить в бд конечно можно)

2022-08-08 21:58 UTC, IvanKoigerov commented on server/prisma/schema.prisma
> +  comments_count Int?
Мне интересно попробоввать триггер написать, поэтому попробую наверное через него
Если не получить на бэке попробую

2022-08-10 16:48 UTC, crutch12 commented
> > А спрашиваю зачем)
> 
> Я там мем скинул, потом понял что не смешной) (Не по теме коммент был)

![image](https://user-images.githubusercontent.com/19373212/183967738-eca64c14-50ee-4479-80ed-39b7807815fa.png)

Почта всё помнит :)

2022-08-27 22:40 UTC, IvanKoigerov commented
@Stilwuc 
Вроде что-то сделал)
Не смог нормально найти как сделать рекурсивный запрос, хотел сначала через sql сделать, но не получилось
Сделал Middleware для того, чтобы хранить в бд количество комментов

2022-08-28 09:58 UTC, Stilwuc approved these changes
Гуд, можешь мержить 👍 
На будущее любую логику (в твоем случае бэка) старайся по файлам раскидывать, а то у тебя сейчас в одном файле и роутинг, и startup и seeds
Было бы намного читаемей если бы это было 3 файла

2022-08-28 10:02 UTC, IvanKoigerov commented
По началу маленький файл был, поэтому не разбивал, а сейчас да, надо было уже разбивать

2022-08-28 10:02 UTC, merged